"""Gazebo bridge: physics + ArduPilot-native flood-town sorties.

Target stack (lab machine):

* **Gazebo Harmonic (gz-sim 8)** + ArduPilot SITL via MAVLink
  (``arducopter --model gazebo-iris`` or the ``gazebo`` backend), ROS 2
  optional — this bridge speaks plain MAVLink + gz-transport CLI topics, so
  it works with or without a ROS install.
* This repo's flood town as SDF: ``worlds/flood_town/flood_town.sdf``,
  generated from ``sar/sim/flood_scene.py`` by :func:`gazebo_world_sdf` so
  all three backends share one town.

Sensor mapping in the SDF world:

* RGB camera (1280x720 @15) + depth camera + **thermal camera plugin**
  (``gz::sim::systems::ThermalCamera``, per-link temperatures) — Gazebo is
  the only backend here with a *native* LWIR sensor model.
* GPU LiDAR (16-channel, 12 m) + IMU + GPS + barometer + magnetometer.
* Water surface: semi-transparent plane + buoyancy plugin hooks for future
  floating-victim drift.

Like the AirSim bridge, everything here degrades cleanly: :func:`gazebo_available`
probes for ``gz`` / ``ign`` binaries and the ArduPilot SITL binary, and the
flood runner falls through to headless when they are absent.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from sar.sim.flood_scene import FloodScene


def gazebo_available() -> Tuple[bool, str]:
    gz = shutil.which("gz") or shutil.which("ign")
    if gz is None:
        return False, "no `gz`/`ign` binary on PATH (install Gazebo Harmonic)"
    sitl = shutil.which("arducopter") or shutil.which("arducopter-sitl")
    extra = " + arducopter SITL" if sitl else " (ArduPilot SITL not found; MiniSITL fallback)"
    try:
        out = subprocess.run([gz, "sim", "--versions"], capture_output=True,
                             text=True, timeout=10)
        ver = (out.stdout or out.stderr).strip().splitlines()
        ver = ver[0][:60] if ver else "unknown version"
    except Exception as exc:
        return False, f"`gz` present but not runnable ({exc})"
    return True, f"{gz} ({ver}){extra}"


# --------------------------------------------------------------------------- #
# SDF generation (runs anywhere — pure file output)
# --------------------------------------------------------------------------- #
_SDF_HEAD = """<?xml version="1.0"?>
<!-- Flood town for SIH26177 SAR sorties.  GENERATED by sar/sim/gazebo_bridge.py
     from sar/sim/flood_scene.py — do not hand-edit; regenerate instead:
       python3 -c "from sar.sim.flood_scene import build_flood_town; \\
                   from sar.sim.gazebo_bridge import gazebo_world_sdf as g; \\
                   g(build_flood_town(), 'worlds/flood_town/flood_town.sdf')" -->
<sdf version="1.9">
  <world name="flood_town">
    <physics name="dart" type="dart"><max_step_size>0.002</max_step_size></physics>
    <scene><shadows>true</shadows><grid>false</grid></scene>
    <light name="sun" type="directional">
      <direction>-0.4 0.35 -0.85</direction><diffuse>0.9 0.9 0.85 1</diffuse>
    </light>
    <spherical_coordinates><latitude_deg>26.14</latitude_deg>
      <longitude_deg>91.74</longitude_deg><elevation>55.0</elevation>
    </spherical_coordinates>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
"""

_SDF_TAIL = """  </world>
</sdf>
"""

_UAV_SDF = """
    <!-- SAR quadrotor: RGB + thermal + depth + LiDAR + nav sensors -->
    <model name="sar_drone">
      <pose>0 0 45 0 0 0</pose>
      <link name="body">
        <inertial><mass>2.4</mass>
          <inertia><ixx>0.05</ixx><iyy>0.05</iyy><izz>0.09</izz></inertia></inertial>
        <collision name="c"><geometry><box><size>0.55 0.55 0.18</size></box></geometry></collision>
        <visual name="v"><geometry><box><size>0.55 0.55 0.18</size></box></geometry>
          <material><diffuse>0.9 0.25 0.15 1</diffuse></material></visual>
        <sensor name="rgb" type="camera">
          <camera><horizontal_fov>1.15</horizontal_fov>
            <image><width>1280</width><height>720</height></image>
            <clip><near>0.5</near><far>400</far></clip></camera>
          <always_on>true</always_on><update_rate>15</update_rate>
          <topic>/sar/rgb</topic>
        </sensor>
        <sensor name="thermal" type="thermal_camera">
          <camera><horizontal_fov>1.0</horizontal_fov>
            <image><width>320</width><height>240</height></image>
            <clip><near>0.5</near><far>400</far></clip></camera>
          <always_on>true</always_on><update_rate>9</update_rate>
          <topic>/sar/thermal</topic>
        </sensor>
        <sensor name="depth" type="depth_camera">
          <camera><horizontal_fov>1.15</horizontal_fov>
            <image><width>640</width><height>480</height></image>
            <clip><near>0.5</near><far>120</far></clip></camera>
          <always_on>true</always_on><update_rate>10</update_rate>
          <topic>/sar/depth</topic>
        </sensor>
        <sensor name="lidar" type="gpu_lidar">
          <always_on>true</always_on><update_rate>10</update_rate>
          <topic>/sar/lidar</topic>
          <gz:sim:sensor><lidar><horizontal><samples>720</samples>
            <min_angle>-3.14159</min_angle><max_angle>3.14159</max_angle></horizontal>
            <vertical><samples>16</samples><min_angle>-0.26</min_angle>
            <max_angle>0.26</max_angle></vertical>
            <range><min>0.3</min><max>12.0</max></range></lidar></gz:sim:sensor>
        </sensor>
        <sensor name="imu" type="imu"><always_on>true</always_on>
          <update_rate>200</update_rate><topic>/sar/imu</topic></sensor>
        <sensor name="gps" type="navsat"><always_on>true</always_on>
          <update_rate>5</update_rate><topic>/sar/gps</topic></sensor>
      </link>
      <plugin filename="gz-sim-multicopter-motor-model-system"
              name="gz::sim::systems::MulticopterMotorModel">
        <robotNamespace>sar</robotNamespace><jointName>rotor</jointName>
      </plugin>
    </model>
"""


def gazebo_world_sdf(scene: FloodScene, out: Optional[Path] = None,
                     max_houses: int = 60) -> str:
    """Render the flood town as a Gazebo SDF world string (and file)."""
    parts = [_SDF_HEAD]
    half = scene.size_m / 2.0
    parts.append(f"""
    <model name="ground"><static>true</static>
      <link name="l"><collision name="c">
        <geometry><plane><normal>0 0 1</normal>
          <size>{scene.size_m * 1.6} {scene.size_m * 1.6}</size></plane></geometry>
      </collision><visual name="v">
        <geometry><plane><normal>0 0 1</normal>
          <size>{scene.size_m * 1.6} {scene.size_m * 1.6}</size></plane></geometry>
        <material><diffuse>0.42 0.40 0.36 1</diffuse></material>
      </visual></link></model>
    <model name="flood_water"><static>true</static>
      <pose>0 0 {scene.water_level_m} 0 0 0</pose>
      <link name="l"><visual name="v">
        <geometry><plane><normal>0 0 1</normal>
          <size>{scene.size_m * 1.2} {scene.size_m * 1.2}</size></plane></geometry>
        <material><diffuse>0.26 0.36 0.44 0.82</diffuse></material>
      </visual></link></model>""")
    for i, h in enumerate(scene.houses[:max_houses]):
        parts.append(f"""
    <model name="house_{i:02d}"><static>true</static>
      <pose>{-h.e:.2f} {-h.n:.2f} {h.h_m / 2:.2f} 0 0 0</pose>
      <link name="l">
        <visual name="walls"><pose>0 0 0 0 0 0</pose>
          <geometry><box><size>{h.w_m} {h.d_m} {h.h_m}</size></box></geometry>
          <material><diffuse>0.62 0.58 0.52 1</diffuse></material></visual>
        <visual name="roof"><pose>0 0 {h.h_m / 2 + 0.4:.2f} 0 0 0</pose>
          <geometry><box><size>{h.w_m + 0.6:.1f} {h.d_m + 0.6:.1f} 0.25</size></box></geometry>
          <material><diffuse>0.59 0.55 0.51 1</diffuse></material></visual>
        <sensor name="t" type="thermal_camera"/>  <!-- inherits link temp -->
      </link></model>""")
    for i, s in enumerate(scene.survivors):
        z = scene.water_level_m + (0.4 if s.in_water else (3.6 if s.on_roof else 0.5))
        parts.append(f"""
    <model name="victim_{s.sid}"><static>true</static>
      <pose>{-s.e:.2f} {-s.n:.2f} {z:.2f} 0 0 0</pose>
      <link name="l"><visual name="v">
        <geometry><capsule><radius>0.22</radius><length>0.9</length></capsule></geometry>
        <material><diffuse>{s.clothing[0]/255:.2f} {s.clothing[1]/255:.2f} {s.clothing[2]/255:.2f} 1</diffuse></material>
      </visual></link></model>""")
    parts.append(_UAV_SDF)
    parts.append(_SDF_TAIL)
    sdf = "\n".join(parts)
    if out is not None:
        out = Path(out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(sdf)
    return sdf


def gazebo_launch_hint(world_path: str = "worlds/flood_town/flood_town.sdf") -> str:
    return (
        "# Terminal 1 — Gazebo flood town:\n"
        f"  gz sim {world_path} -r\n"
        "# Terminal 2 — ArduPilot SITL bound to it (or MiniSITL fallback):\n"
        "  sim_vehicle.py -v ArduCopter -f gazebo-iris --console --map\n"
        "# Terminal 3 — the flood sortie against live MAVLink:\n"
        "  python3 scripts/run_flood_sim.py --backend gazebo --duration 300\n")


__all__ = ["gazebo_available", "gazebo_world_sdf", "gazebo_launch_hint"]
