#!/usr/bin/env python3
"""Build the SIH 2026 pitch deck (PPTX) for the SAHYOG search-and-rescue drone.

Follows the Smart India Hackathon presentation structure (title → problem →
solution → architecture → innovation → validation → impact → future scope) and
embeds the figures generated by ``make_pitch_assets.py`` plus the measured
results from the real artifacts in ``artifacts/``.

Run:  python scripts/make_pitch_ppt.py
Output: docs/SIH2026_SAHYOG_Presentation.pptx
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts._bootstrap import bootstrap  # noqa: E402

bootstrap()

from pptx import Presentation  # noqa: E402
from pptx.util import Inches, Pt  # noqa: E402
from pptx.dml.color import RGBColor  # noqa: E402
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR  # noqa: E402
from pptx.enum.shapes import MSO_SHAPE  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
PITCH = ROOT / "docs" / "assets" / "pitch"
OUT = ROOT / "docs" / "SIH2026_SAHYOG_Presentation.pptx"

# ---- palette ---------------------------------------------------------------
BG = RGBColor(0x0B, 0x12, 0x20)
PANEL = RGBColor(0x11, 0x1A, 0x2B)
INK = RGBColor(0xE5, 0xED, 0xF8)
MUTED = RGBColor(0x8E, 0xA3, 0xC0)
GREEN = RGBColor(0x22, 0xC5, 0x5E)
CYAN = RGBColor(0x38, 0xBD, 0xF8)
AMBER = RGBColor(0xF5, 0x9E, 0x0B)
RED = RGBColor(0xDC, 0x26, 0x26)

FONT = "Calibri"
SW, SH = Inches(13.333), Inches(7.5)


def _solid(shape, color):
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()


def add_rect(slide, x, y, w, h, color, radius=None):
    shp = slide.shapes.add_shape(
        MSO_SHAPE.ROUNDED_RECTANGLE if radius else MSO_SHAPE.RECTANGLE,
        Inches(x), Inches(y), Inches(w), Inches(h))
    _solid(shp, color)
    if radius:
        try:
            shp.adjustments[0] = radius
        except Exception:
            pass
    shp.shadow.inherit = False
    return shp


def add_text(slide, x, y, w, h, runs, size=14, color=INK, bold=False,
             align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, font=FONT,
             line_spacing=1.0, space_after=2):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    if isinstance(runs, str):
        runs = [[(runs, {})]]
    for i, para in enumerate(runs):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = line_spacing
        p.space_after = Pt(space_after)
        if not isinstance(para, (list, tuple)):
            para = [(para, {})]
        for text, kw in para:
            r = p.add_run()
            r.text = text
            f = r.font
            f.name = kw.get("font", font)
            f.size = Pt(kw.get("size", size))
            f.bold = kw.get("bold", bold)
            f.color.rgb = kw.get("color", color)
            if kw.get("italic"):
                f.italic = True
    return box


def bullets(slide, x, y, w, h, items, size=14, color=INK, marker="▸",
            marker_color=GREEN, gap=4, line_spacing=1.05):
    paras = []
    for it in items:
        if isinstance(it, tuple):
            lead, rest = it
            paras.append([(marker + "  ", {"color": marker_color, "bold": True}),
                          (lead, {"bold": True, "color": color}),
                          (rest, {"color": MUTED})])
        else:
            paras.append([(marker + "  ", {"color": marker_color, "bold": True}),
                          (it, {"color": color})])
    return add_text(slide, x, y, w, h, paras, size=size, line_spacing=line_spacing,
                    space_after=gap)


def add_pic(slide, path, x, y, w=None, h=None):
    kw = {}
    if w is not None:
        kw["width"] = Inches(w)
    if h is not None:
        kw["height"] = Inches(h)
    return slide.shapes.add_picture(str(path), Inches(x), Inches(y), **kw)


def header(slide, kicker, title, accent=GREEN, title_size=30):
    add_rect(slide, 0, 0, 13.333, 7.5, BG)
    add_rect(slide, 0.55, 0.42, 0.14, 0.86, accent)
    add_text(slide, 0.85, 0.34, 11.9, 0.3, kicker.upper(), size=11, color=accent,
             bold=True)
    add_text(slide, 0.85, 0.62, 12.0, 0.9, title, size=title_size, color=INK,
             bold=True)


def footer(slide, n):
    add_text(slide, 0.55, 7.08, 8.0, 0.3, "SAHYOG · SIH 2026 · PS 26177",
             size=9, color=MUTED)
    add_text(slide, 12.35, 7.08, 0.5, 0.3, str(n), size=9, color=MUTED,
             align=PP_ALIGN.RIGHT)


def stat_card(slide, x, y, w, h, value, label, vcolor=GREEN):
    add_rect(slide, x, y, w, h, PANEL, radius=0.08)
    add_rect(slide, x, y, 0.06, h, vcolor)
    add_text(slide, x + 0.18, y + 0.12, w - 0.3, 0.62, value, size=26, color=vcolor,
             bold=True)
    add_text(slide, x + 0.18, y + h - 0.5, w - 0.3, 0.35, label, size=11,
             color=MUTED)


def build() -> str:
    prs = Presentation()
    prs.slide_width = SW
    prs.slide_height = SH
    BLANK = prs.slide_layouts[6]

    # ========================================================= 1 · TITLE =====
    s = prs.slides.add_slide(BLANK)
    add_rect(s, 0, 0, 13.333, 7.5, BG)
    add_rect(s, 0, 0, 13.333, 0.14, GREEN)
    add_rect(s, 0, 7.36, 13.333, 0.14, GREEN)
    add_text(s, 0.9, 1.15, 11.5, 0.4, "SMART INDIA HACKATHON 2026 · ROBOTICS & DRONES",
             size=13, color=CYAN, bold=True)
    add_text(s, 0.9, 1.75, 11.9, 1.6, "SAHYOG", size=66, color=INK, bold=True)
    add_text(s, 0.9, 2.95, 11.9, 0.8,
             "Autonomous AI Search-&-Rescue VTOL Drone with a Physics-Engine for "
             "GNSS-denied, low-connectivity disaster zones", size=22, color=GREEN,
             bold=True)
    add_text(s, 0.9, 4.05, 11.9, 0.5,
             "RGB + LWIR edge AI  ·  physics-informed survivor identification  ·  "
             "ExpressLRS / MAVLink reporting  ·  payload delivery + safe routing",
             size=15, color=MUTED)
    add_rect(s, 0.9, 4.95, 11.5, 1.25, PANEL, radius=0.06)
    add_text(s, 1.15, 5.08, 11.0, 0.4,
             [[("Problem Statement 26177 · Qualcomm Inc · ", {"color": INK, "bold": True}),
               ("“A deployable AI-powered autonomous drone that aids search-and-rescue "
                "operations by detecting people and hazards, improving responder safety "
                "and reducing victim discovery time.”", {"color": MUTED})]], size=13)
    add_text(s, 1.15, 5.72, 11.0, 0.4,
             [[("Team: ", {"color": MUTED}), ("[Team Name]", {"color": INK, "bold": True}),
               ("   ·   Institute: ", {"color": MUTED}),
               ("[Institute Name]", {"color": INK, "bold": True})]], size=13)
    footer(s, 1)

    # ================================================ 2 · PROBLEM ============
    s = prs.slides.add_slide(BLANK)
    header(s, "The problem", "Every hour lost costs lives in a disaster zone", RED)
    bullets(s, 0.85, 1.65, 6.7, 4.9, [
        ("Golden hour. ", "Survival probability falls steeply in the first hours; "
         "current ground assessment is slow, dangerous and resource-heavy."),
        ("GNSS-denied. ", "Floods, quakes and landslides happen under bridges, "
         "collapsed structures, dense canopy and indoors — where GPS fails."),
        ("No connectivity. ", "Disaster zones have no internet, no cellular, and "
         "often no line-of-sight to the command post."),
        ("False confidence. ", "A naive “person detected” pin without honest "
         "uncertainty sends responders into hazard or the wrong place."),
        ("Hazards everywhere. ", "Floodwater, fire, debris, live wires and unstable "
         "structures kill rescuers, not just victims."),
    ], size=15, gap=10)
    add_text(s, 0.85, 6.55, 6.7, 0.4,
             [[("The jury question we built for: “who faces this today, and why "
               "hasn’t it been solved?” — because connectivity, GNSS and trustable "
               "detection are exactly what a disaster removes.",
               {"color": MUTED, "italic": True})]], size=11)
    add_rect(s, 7.85, 1.6, 4.75, 5.0, PANEL, radius=0.05)
    if (PITCH / "pitch_01_problem.png").exists():
        add_pic(s, PITCH / "pitch_01_problem.png", 8.05, 1.85, 4.35)
    add_text(s, 7.85, 6.72, 4.75, 0.4, "Survival vs time — every minute matters",
             size=10, color=MUTED, align=PP_ALIGN.CENTER)
    footer(s, 2)

    # ================================================= 3 · SOLUTION ==========
    s = prs.slides.add_slide(BLANK)
    header(s, "Our solution", "One airframe, six capabilities — all on-device", GREEN)
    add_text(s, 0.85, 1.55, 11.7, 0.8,
             "A 3D-printed VTOL drone on an H743-Wing flight controller that searches "
             "autonomously, identifies survivors and hazards on the edge, navigates "
             "without GNSS, and reports only verified, geo-tagged, actionable "
             "intelligence over a radio link that survives outages.",
             size=15, color=MUTED)
    cards = [
        ("01", "RGB + LWIR detection", "YOLO on fused visible + thermal imagery for "
         "people and hazards (flood, fire, debris, collapse).", CYAN),
        ("02", "Physics-engine ID", "Posture, thermal physiology, decoy veto and "
         "triage from physical models — the novelty.", AMBER),
        ("03", "GNSS-denied nav", "EKF3 external-nav switching to visual-inertial "
         "odometry, with honest position uncertainty.", GREEN),
        ("04", "Offline comms", "ExpressLRS + MAVLink + LoRa store-and-forward; "
         "verified reports, not video streams.", GREEN),
        ("05", "Geo-tagged map", "Survivor & hazard pins with error ellipses that "
         "grow correctly when the fix degrades.", CYAN),
        ("06", "Rescue execution", "Ballistic payload drop and A* safe routes for "
         "ground & boat teams.", RED),
    ]
    for i, (num, title, body, col) in enumerate(cards):
        x = 0.85 + (i % 3) * 3.95
        y = 2.55 + (i // 3) * 2.15
        add_rect(s, x, y, 3.75, 1.95, PANEL, radius=0.06)
        add_rect(s, x, y, 3.75, 0.07, col)
        add_text(s, x + 0.22, y + 0.16, 3.3, 0.4, num, size=18, color=col, bold=True)
        add_text(s, x + 0.22, y + 0.56, 3.3, 0.5, title, size=14.5, color=INK, bold=True)
        add_text(s, x + 0.22, y + 1.02, 3.35, 0.85, body, size=11, color=MUTED,
                 line_spacing=1.03)
    footer(s, 3)

    # ================================================ 4 · ARCHITECTURE =======
    s = prs.slides.add_slide(BLANK)
    header(s, "How it works", "End-to-end system architecture", CYAN)
    if (PITCH / "pitch_arch.png").exists():
        add_pic(s, PITCH / "pitch_arch.png", 0.85, 1.5, 11.65)
    add_text(s, 0.85, 6.35, 11.7, 0.6,
             "Sensing → on-device AI → navigation → comms → command centre. Every "
             "block is a real, tested module in this repository (134 unit tests).",
             size=12, color=MUTED)
    footer(s, 4)

    # =============================================== 5 · NOVELTY =============
    s = prs.slides.add_slide(BLANK)
    header(s, "The novelty", "A physics engine inside the AI", AMBER)
    if (PITCH / "pitch_physics.png").exists():
        add_pic(s, PITCH / "pitch_physics.png", 0.85, 1.5, 11.65)
    bullets(s, 0.85, 5.35, 11.9, 1.6, [
        ("Posture from physics, not pixels. ", "A nadir thermal blob cannot show a "
         "posture directly — so we infer it from water depth, elongation, motion and "
         "nearby-hazard context, each a physical quantity."),
        ("Thermal physiology. ", "Apparent temperature + trend maps to cold-water "
         "survival / wind-chill models → a time-criticality and triage tier, with "
         "uncertainty reported instead of a diagnosis."),
        ("Decoy veto. ", "Morphological, radiometric and kinematic rules reject "
         "sun-heated roofs, vehicles, hot rocks and glints."),
        ("Actuation. ", "Ballistic drop (quadratic drag + wind) and A* routing over "
         "water, debris and hazard severity."),
    ], size=12.5, gap=4)
    footer(s, 5)

    # ============================================= 6 · PERCEPTION ============
    s = prs.slides.add_slide(BLANK)
    header(s, "Perception", "RGB + LWIR + YOLO, fused on the edge", CYAN)
    if (PITCH / "pitch_03_detection.png").exists():
        add_pic(s, PITCH / "pitch_03_detection.png", 0.85, 1.55, 6.6)
    bullets(s, 7.75, 1.7, 5.0, 5.0, [
        ("Two sensors. ", "RGB for saliency & shape; LWIR for radiometry, vitals and "
         "night operation."),
        ("YOLO family. ", "YOLOv8/YOLO11 backends behind one interface — heuristic "
         "audited ensemble flies today; INT8/QNN weights drop in when trained."),
        ("Cross-modal veto. ", "A person must survive both modalities; physics-gated "
         "so a warm roof is rejected on geometry."),
        ("Geometry gate. ", "Ground-sample-distance aware: detection rate is governed "
         "by altitude × lens × target extent."),
    ], size=13, gap=8)
    add_text(s, 7.75, 6.2, 5.0, 0.6,
             [[("Measured: recall 1.00 of resolvable targets at 35/50/70 m; the work "
               "is clutter rejection (precision), not blindness.",
               {"color": MUTED, "italic": True})]], size=11)
    footer(s, 6)

    # ============================================= 7 · GNSS-DENIED ============
    s = prs.slides.add_slide(BLANK)
    header(s, "Navigation", "Flying where there is no GPS", GREEN)
    if (PITCH / "pitch_04_gps.png").exists():
        add_pic(s, PITCH / "pitch_04_gps.png", 0.85, 1.55, 6.6)
    bullets(s, 7.75, 1.7, 5.0, 5.0, [
        ("EKF3 source sets. ", "GNSS (set 1) ↔ external-nav VIO (set 2), switched "
         "by a quality monitor with hysteresis."),
        ("Honest uncertainty. ", "A position’s reported sigma bounds its true error; "
         "a survivor pin under denial is visibly less trustworthy."),
        ("Proven in-sim. ", "Mid-sortie denial at 100 s: source switched, a survivor "
         "was geo-tagged at dead-reckoning sigma 2.1 m, GNSS restored."),
        ("On hardware. ", "ArduPilot EK3_SRCn_POSXY/VELXY = 6 wired for a real VIO "
         "feed (OpenVINS / VOXL)."),
    ], size=13, gap=8)
    footer(s, 7)

    # ================================================ 8 · COMMS ===============
    s = prs.slides.add_slide(BLANK)
    header(s, "Communications", "Verified reports, not video", GREEN)
    if (PITCH / "pitch_05_comms.png").exists():
        add_pic(s, PITCH / "pitch_05_comms.png", 0.85, 1.55, 6.6)
    bullets(s, 7.75, 1.7, 5.0, 5.0, [
        ("ExpressLRS. ", "Control + short MAVLink status on the 2.4 GHz/900 MHz "
         "link — always up, but not a data link."),
        ("LoRa 900. ", "Structured survivor/hazard alerts over kilometres, "
         "non-line-of-sight."),
        ("Store-and-forward. ", "Byte-bounded priority queue with tier-aware "
         "eviction and spatial coalescing — a link outage costs latency, never a "
         "survivor."),
        ("No video. ", "Lightweight reports only; imagery is optional bulk traffic "
         "on a Wi-Fi bridge."),
    ], size=13, gap=8)
    add_text(s, 7.75, 6.2, 5.0, 0.6,
             [[("Measured: 96.9–97.8% packet success on the LoRa model across a full "
               "sortie with a 200 s outage.", {"color": MUTED, "italic": True})]],
             size=11)
    footer(s, 8)

    # =============================================== 9 · RESCUE ===============
    s = prs.slides.add_slide(BLANK)
    header(s, "Rescue execution", "Payload to the victim, path for the team", RED)
    if (PITCH / "pitch_06_rescue.png").exists():
        add_pic(s, PITCH / "pitch_06_rescue.png", 0.85, 1.55, 6.6)
    bullets(s, 7.75, 1.7, 5.0, 5.0, [
        ("Ballistic release. ", "Quadratic drag + wind → an optimal release point "
         "the aircraft flies to before dropping; parachute delay modelled."),
        ("Precision. ", "Release-lead approach cut drop error from ~62 m (drop "
         "where-you-are) to 5.6–18.4 m."),
        ("A* routing. ", "Ground & boat teams get a safe corridor that respects "
         "wading depth, debris, structures and hazard severity."),
        ("Equipment matched. ", "Flotation for in-water victims, trauma kit, thermal "
         "blanket, beacon — chosen by the identification profile."),
    ], size=13, gap=8)
    footer(s, 9)

    # ==================================== 10 · SIMULATION & VALIDATION ========
    s = prs.slides.add_slide(BLANK)
    header(s, "Validation", "Simulated first, flown second", CYAN)
    bullets(s, 0.85, 1.6, 5.9, 4.6, [
        ("MiniSITL sorties. ", "Full MAVLink mission loop: search → detect → report, "
         "with GNSS denial and link outages injected."),
        ("Gazebo. ", "A flood-town SDF world (buildings, water, victims) ships in "
         "worlds/flood_town/ for ROS/Gazebo testing."),
        ("AirSim. ", "A bridge module maps AirSim APIs to the same world model for "
         "photo-real flood scenes (requires Unreal Engine + GPU)."),
        ("Real drone. ", "H743-Wing + LWIR + companion computer; every bring-up step "
         "documented, arming gated behind a field checklist."),
    ], size=13.5, gap=8)
    add_rect(s, 7.0, 1.6, 5.5, 5.1, PANEL, radius=0.05)
    add_text(s, 7.25, 1.75, 5.0, 0.4, "Measured results (this build)", size=14,
             color=CYAN, bold=True)
    rows = [
        ("Autonomy tests", "134 passed · 2 skipped"),
        ("Rescue sortie (flood)", "8 survivors identified"),
        ("Payload drops", "4 drops · mean error 17.1 m"),
        ("Best drop", "5.6 m (was 62 m naive)"),
        ("Detection recall / precision", "0.80 / 0.57"),
        ("Coverage (180 s sortie)", "30.6% effective"),
        ("Geo-tag error (mean)", "16.3 m"),
        ("Packet success (LoRa)", "96.9% over 223 packets"),
    ]
    y = 2.25
    for k, v in rows:
        add_text(s, 7.25, y, 2.7, 0.4, k, size=11.5, color=MUTED)
        add_text(s, 10.0, y, 2.4, 0.4, v, size=11.5, color=INK, bold=True,
                 align=PP_ALIGN.RIGHT)
        y += 0.47
    footer(s, 10)

    # ================================================= 11 · HARDWARE =========
    s = prs.slides.add_slide(BLANK)
    header(s, "Hardware", "Built to be built — and flown", AMBER)
    hw = [
        ("H743-Wing flight controller", "Latest STM32H743 autopilot, ArduPilot "
         "EKF3, multi-source aiding.", GREEN),
        ("3D-printed airframe", "Printed on our own printer; VTOL for tight urban "
         "and rooftop operations.", GREEN),
        ("LWIR thermal core", "Radiometric thermal for vitals, night and decoy "
         "rejection.", CYAN),
        ("RGB camera", "Saliency, shape and hazard context.", CYAN),
        ("ExpressLRS + LoRa", "Control/status link plus the offline data link.",
         AMBER),
        ("Companion computer", "Runs the on-device AI stack (NPU-ready: QCS6490 / "
         "Jetson).", AMBER),
        ("Rescue payload bay", "Interchangeable flotation, first-aid, blanket and "
         "beacon payloads.", RED),
        ("Ground control station", "Live + offline-replay command dashboard.", RED),
    ]
    for i, (t, b, col) in enumerate(hw):
        x = 0.85 + (i % 2) * 5.95
        y = 1.6 + (i // 2) * 1.32
        add_rect(s, x, y, 5.75, 1.15, PANEL, radius=0.07)
        add_rect(s, x, y, 0.07, 1.15, col)
        add_text(s, x + 0.22, y + 0.12, 5.3, 0.4, t, size=13.5, color=INK, bold=True)
        add_text(s, x + 0.22, y + 0.52, 5.35, 0.55, b, size=11, color=MUTED,
                 line_spacing=1.0)
    footer(s, 11)

    # ================================================ 12 · TECH STACK ========
    s = prs.slides.add_slide(BLANK)
    header(s, "Technology", "Stack and where each piece runs", CYAN)
    stack = [
        ("Detection AI", "YOLOv8 / YOLO11 · ONNX Runtime · INT8 / QNN",
         "Companion computer / NPU", CYAN),
        ("Physics engine", "Thermal physiology · posture · ballistic drop · A*",
         "On-device Python (numpy)", AMBER),
        ("Autopilot", "ArduPilot · MAVLink · EKF3 external-nav",
         "H743-Wing flight controller", GREEN),
        ("Comms", "ExpressLRS (CRSF) · LoRa 900 · MAVLink telemetry",
         "On-aircraft radios", GREEN),
        ("Simulation", "MiniSITL · Gazebo (SDF) · AirSim bridge · flood renderer",
         "Development laptop / CI", CYAN),
        ("Dashboard", "FastAPI + canvas command centre · offline replay",
         "Ground station", RED),
        ("Language", "Python 3.11 · numpy · scipy · pytest (134 tests)",
         "End-to-end", INK),
    ]
    y = 1.55
    for name, detail, where, col in stack:
        add_rect(s, 0.85, y, 11.65, 0.72, PANEL, radius=0.12)
        add_rect(s, 0.85, y, 0.06, 0.72, col)
        add_text(s, 1.1, y + 0.07, 3.1, 0.6, name, size=13, color=INK, bold=True)
        add_text(s, 4.3, y + 0.07, 6.4, 0.6, detail, size=12, color=MUTED)
        add_text(s, 10.8, y + 0.07, 1.6, 0.6, where, size=11, color=col,
                 align=PP_ALIGN.RIGHT)
        y += 0.79
    footer(s, 12)

    # ================================================= 13 · IMPACT ===========
    s = prs.slides.add_slide(BLANK)
    header(s, "Impact", "Faster, safer rescue intelligence", GREEN)
    stat_card(s, 0.85, 1.7, 2.9, 1.9, "min–hours", "to first verified survivor pin",
              GREEN)
    stat_card(s, 3.95, 1.7, 2.9, 1.9, "100%", "on-device — works with zero "
              "connectivity", CYAN)
    stat_card(s, 7.05, 1.7, 2.9, 1.9, "5.6 m", "precision payload delivery", AMBER)
    stat_card(s, 10.15, 1.7, 2.9, 1.9, "±m", "honest geo-tag uncertainty", RED)
    bullets(s, 0.85, 4.0, 11.7, 2.6, [
        ("For responders. ", "A geo-tagged, triage-ordered survivor & hazard map "
         "with safe access routes — before boots hit the ground."),
        ("For victims. ", "Immediate payload (flotation, first-aid, blanket, beacon) "
         "while help is routed."),
        ("For the state. ", "Scales from one drone to a fleet; belief maps are "
         "serialisable for multi-aircraft hand-off; offline by construction."),
    ], size=14, gap=10)
    footer(s, 13)

    # ================================================ 14 · FUTURE ============
    s = prs.slides.add_slide(BLANK)
    header(s, "Road ahead", "Future scope", AMBER)
    bullets(s, 0.85, 1.7, 11.7, 4.6, [
        ("Trained thermal weights. ", "HIT-UAV / AIResQ / SARD fine-tune + INT8/QNN "
         "quantisation on the Qualcomm NPU (pipeline and gates already built)."),
        ("Real VIO front end. ", "OpenVINS / VINS-Fusion publishing MAVLink "
         "ODOMETRY — the consumer side is already tested against that stream."),
        ("Multi-aircraft hand-off. ", "Belief-map resume across batteries and "
         "airframes for whole-basin coverage."),
        ("Active learning. ", "Field false alarms looped back into the detector."),
        ("Hazard-model priors. ", "RescueNet segmentation feeding the cross-modal "
         "veto as a prior."),
        ("Autonomous arm-and-fly. ", "Deliberately gated behind the field-test "
         "checklist until a human has flight-validated it."),
    ], size=14, gap=10)
    footer(s, 14)

    # ================================================ 15 · THANKS ============
    s = prs.slides.add_slide(BLANK)
    add_rect(s, 0, 0, 13.333, 7.5, BG)
    add_rect(s, 0, 0, 13.333, 0.14, GREEN)
    add_rect(s, 0, 7.36, 13.333, 0.14, GREEN)
    add_text(s, 0.9, 2.3, 11.5, 1.2, "Thank you", size=60, color=INK, bold=True)
    add_text(s, 0.9, 3.5, 11.5, 0.6,
             "SAHYOG — search fast, report truth, rescue safely.", size=20,
             color=GREEN, bold=True)
    add_text(s, 0.9, 4.5, 11.5, 0.5,
             "Live demo: mission command centre · offline mission replay · full "
             "source and 134 tests in this repository", size=14, color=MUTED)
    add_text(s, 0.9, 5.4, 11.5, 0.5,
             "[Team name]  ·  [Institute]  ·  SIH 2026 · Robotics & Drones",
             size=13, color=MUTED)
    footer(s, 15)

    prs.save(OUT)
    return str(OUT)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Build the SIH 2026 SAHYOG pitch deck (PPTX) into docs/.")
    parser.parse_args(argv)
    print(f"pitch deck -> {build()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
